
[functions.generate-monthly-bills]
enabled = true
verify_jwt = true
import_map = "./functions/generate-monthly-bills/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-monthly-bills/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-monthly-bills/*.html" ]

[functions.test-cunc]
enabled = true
verify_jwt = true
import_map = "./functions/test-cunc/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/test-cunc/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/test-cunc/*.html" ]
